### ISSUE TITLE
iRODS 4.x Dynamic PEP's not being triggered

### ISSUE THREAD

**Issue by ilarik** [UtrechtUniversity/davrods#18] opened 2019-12-10 10:51 UTC
Hi,

I'm not sure whether this would be a request for enhancement or a bug report, but in any case I decided to report the following. Due to certain workarounds we had to establish in our environment after iRODS 4.2 upgrade, we had to start using the so called dynamic policy enforcement points, i.e `pep_api_data_obj_put_post` instead of `acPostProcForPut`.

For some reason Davrods seems to trigger only `acPostProcForPut`.

Test scenario using `irods-provisioner` and spinning up a test cluster.
```
$ cd /tmp 
$ git clone https://github.com/KTH-PDC/irods-provisioner.git
```
```
$ cd irods-provisioner
$ vagrant up
$ ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -b -i hosts-test irods-cluster.yml
```
```
$ vagrant ssh rodsmaster1
[vagrant@rodsmaster1 ~]$ sudo su - irods
-bash-4.2$ cat >>/etc/irods/core-override.re 

acPostProcForPut
{
	writeLine("serverLog", "acPostProcForPut: objPath='$objPath'");
}

pep_api_data_obj_put_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT)
{
	*objPath = *DATAOBJINP.obj_path;
   	writeLine("serverLog", "pep_api_data_obj_put_post: objPath = '*objPath'");	
}
^D
```
At the host one can mount the WebDAV endpoint (macOS commands displayed):
```
$ mkdir -p /tmp/webdav
$ mount_webdav -i http://rodsfront1:8443/home/rods/ /tmp/webdav
Username: rods
Password:
```
```
$ echo blaa > blaa.txt
$ cp blaa.txt /tmp/webdav 
```
And afterwards we can observe in `rodsLog`:
```
Dec 10 10:05:16 pid:12570 NOTICE: writeLine: inString = acPostProcForPut: objPath='/tempZone/home/rods/blaa.txt'
Dec 10 10:05:16 pid:12570 NOTICE: writeLine: inString = acPostProcForPut: objPath='/tempZone/home/rods/blaa.txt'
```

**Comment by trel** [comment] 2019-12-10 12:49
Is this due to davrods using open-write-close?  rather than put?

**Comment by cjsmeele** [comment] 2019-12-10 15:22
Yes, it appears to be caused by the different API usage by davrods vs iput.
I haven't dived very deep into the underlying implementation of iput, but the `rc` function it uses to reach the specific "put" api (`rcDataObjPut`, vs Davrods `rcDataObjOpen/Write/Close`) appears to assume access to a local file by name. We cannot use this directly in Davrods, as we do not cache uploaded files - we are always dealing with streams.

It may be possible to reuse/change parts of rcDataObjPut to work without local filesystem access, but taking the complexity of the relevant library parts ([rcPortalOpr.cpp](https://github.com/irods/irods/blob/master/lib/core/src/rcPortalOpr.cpp)) into account, I'm not sure that this belongs in Davrods.

A HTTP PUT is in my understanding still very much a "PUT" in iRODS, but as far as I currently understand, the client library no longer (re: oprType/static peps) has an ergonomic way to signal this without letting it perform on local files like icommands.
I'm interested to hear your thoughts on this.


FWIW: There used to be a similar issue with static PEPs not being triggered in pre-release versions of Davrods (https://github.com/irods/irods/issues/3204 ) which was fixed by setting a `oprType` flag in the request. We still, currently, specify a "PUT" operation type to iRODS, but this has no apparent effect on dynamic PEPs.

---

For now, the API PEPs that are currently triggered by file PUTs through Davrods are:

    pep_api_data_obj_create (only for new files)
    pep_api_data_obj_open (only for existing files)
    pep_api_data_obj_write
    pep_api_data_obj_close

Corresponding resource PEPs are triggered as well, including `pep_resource_modified` at the end of the operation.

**Comment by cjsmeele** [comment] 2020-02-19 20:28
Per https://github.com/DICE-UNC/jargon/issues/349#issuecomment-588414563, this is intentional behavior in iRODS and cannot be influenced by clients using open/write/close.
Using the iput-style `put` API would trigger the associated PEP, but as described above this is not an option for Davrods.

**Closed by cjsmeele** 2020-02-19 20:28 UTC
